"""
Author: Aksel Gundersen
Project: Master thesis – Finite Element Analysis of Composite Laminated Sandwich Structures in Formula Student Chassis Design
Content: Plots convergence metrics from the CSV results generated by FSDT_plate_model.py.
"""

import pandas as pd
import matplotlib.pyplot as plt


plt.rcParams.update({
    "text.usetex": True,
    "font.family": "serif",
    "font.serif": ["Latin Modern Roman"],
    "font.size": 34,
    "axes.labelsize": 34,
    "legend.fontsize": 34,
    "text.latex.preamble": r"\usepackage{amsmath}"
})

DATA_FILE = "convergence_results.csv"

df = pd.read_csv(DATA_FILE)


def plot_metric(metric, ylabel, title):
    """
    Plot a convergence metric against mesh size for each polynomial degree.

    Parameters
    ----------
    metric : str
        Column name in the CSV file to be plotted.
    ylabel : str
        Label for the y-axis.
    title : str
        Plot title.

    Returns
    -------
    None
        Displays the convergence plot.
    """
    plt.figure(figsize=(7.2, 4.8))

    for pe in sorted(df["Pe"].unique()):
        sub = df[df["Pe"] == pe].sort_values("h", ascending=False)
        plt.plot(sub["h"], sub[metric], marker="o", label=rf"$P_e = {pe}$")

    plt.gca().invert_xaxis()
    plt.xlabel(r"$h$")
    plt.ylabel(ylabel)
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()


# Thesis convergence plots.
plot_metric(
    "uz_max",
    r"$\max |u_z|$",
    r"Convergence of transverse displacement",
)

plot_metric(
    "strain_energy",
    r"$U$",
    r"Convergence of strain energy",
)

plot_metric(
    "max_sigma1",
    r"$\max |\sigma_1|$",
    r"Convergence of maximum ply stress $\sigma_1$",
)

plot_metric(
    "max_tau12",
    r"$\max |\tau_{12}|$",
    r"Convergence of in-plane shear stress $\tau_{12}$",
)


# Comparison against a finer reference mesh.
selected = df[(df["h"] == 6) & (df["Pe"] == 2)].iloc[0]
reference = df[(df["h"] == 3) & (df["Pe"] == 2)].iloc[0]

metrics_compare = [
    ("uz_max", r"$\max |u_z|$"),
    ("strain_energy", r"$U$"),
    ("max_sigma1", r"$\max |\sigma_1|$"),
    ("max_tau12", r"$\max |\tau_{12}|$"),
]

labels = []
values = []

for col, label in metrics_compare:
    rel_diff = abs(selected[col] - reference[col]) / abs(reference[col]) * 100.0
    labels.append(label)
    values.append(rel_diff)

plt.figure(figsize=(7.2, 4.8))
plt.bar(labels, values)
plt.ylabel(r"Relative difference [\%]")
plt.title(r"Selected model vs.\ finer reference ($P_e=2$, $h=3$)")
plt.grid(True, axis="y")
plt.tight_layout()
plt.show()